---

config:
    layout: elk
    look: classic
    theme: base
    themeVariables:
        fontFamily: "monospace"
        lineColor: "#D65D0E"

---

flowchart TB
    subgraph Subdomains["_Subdomains_"]
        subgraph Core["_Bounded-Context_"]
            subgraph Infrastructure["_Infrastructure_"]
                subgraph InfrastructureAdapter["_Adapter_"]
                    subgraph InfrastructureCommand["_Command_"]
                        direction LR

                        subgraph InfrastructureCommandUpstream["_Controller_"]
                            InfrastructureCommandUpstreamAdapter[Upstream]
                        end

                        subgraph InfrastructureCommandDownstream["_Repository_"]
                            InfrastructureCommandDownstreamAdapter[Downstream]
                        end

                        InfrastructureCommandUpstream
                        ~~~ InfrastructureCommandDownstream
                    end

                    subgraph InfrastructureQuery["_Query_"]
                        direction LR

                        subgraph InfrastructureQueryUpstream["_Controller_"]
                            InfrastructureQueryUpstreamAdapter[Upstream]
                        end

                        subgraph InfrastructureQueryDownstream["_Repository_"]
                            InfrastructureQueryDownstreamAdapter[Downstream]
                        end

                        InfrastructureQueryUpstream
                        ~~~ InfrastructureQueryDownstream
                    end

                    subgraph InfrastructureGateway["_Gateway_"]
                        direction LR

                        subgraph InfrastructureGatewayUpstream["_Inbound_"]
                            InfrastructureGatewayUpstreamAdapter[Upstream]
                        end

                        subgraph InfrastructureGatewayDownstream["_Outbound_"]
                            InfrastructureGatewayDownstreamAdapter[Downstream]
                        end

                        InfrastructureGatewayUpstream
                        ~~~ InfrastructureGatewayDownstream
                    end

                    InfrastructureCommand
                    ~~~ InfrastructureQuery
                    ~~~ InfrastructureGateway
                end
            end

            subgraph Application["_Application_"]
                subgraph ApplicationContract["_Contract_"]
                    subgraph ApplicationCommand["_Command_"]
                        direction LR

                        subgraph ApplicationCommandContractUpstream["_Controller_"]
                            ApplicationCommandContractUpstreamInterface[Upstream]
                        end

                        subgraph ApplicationCommandContractDownstream["_Repository_"]
                            ApplicationCommandContractDownstreamInterface[Downstream]
                        end

                        ApplicationCommandContractUpstream
                        ~~~ ApplicationCommandContractDownstream
                    end

                    subgraph ApplicationQuery["_Query_"]
                        direction LR

                        subgraph ApplicationQueryContractUpstream["_Controller_"]
                            ApplicationQueryContractUpstreamInterface[Upstream]
                        end

                        subgraph ApplicationQueryContractDownstream["_Repository_"]
                            ApplicationQueryContractDownstreamInterface[Downstream]
                        end

                        ApplicationQueryContractUpstream
                        ~~~ ApplicationQueryContractDownstream
                    end

                    subgraph ApplicationGateway["_Gateway_"]
                        direction LR

                        subgraph ApplicationGatewayInbound["_Inbound_"]
                            ApplicationGatewayUpstream[Upstream]
                        end

                        subgraph ApplicationGatewayOutbound["_Outbound_"]
                            ApplicationGatewayDownstream[Downstream]
                        end

                        ApplicationGatewayInbound
                        ~~~ ApplicationGatewayOutbound
                    end

                    ApplicationCommand
                    ~~~ ApplicationQuery
                    ~~~ ApplicationGateway
                end

                subgraph ApplicationService["_Service_"]
                    Interactor[Interactor]:::implementation
                    ~~~ ProcessManager["Process Manager"]:::implementation
                end
            end

            subgraph Domain[_Domain_]
                subgraph DomainService[_Service_]
                    DomainFactory[Factory]
                    --> DomainAggregate[Aggregate]
                end

                subgraph DomainSchema[_Schema_]
                    DomainEntity[Entity] --> DomainValueObject[Value Object]
                end

                DomainAggregate --> DomainSchema
            end

            Application ~~~~ Domain
            Application ~~~~ Domain
            Application ~~~~ Domain
            Application ~~~~ Domain
            Application ~~~~ Domain
            Application ~~~~ Domain
            Application ~~~~ Domain
            Application ~~~~ Domain
            Application ~~~~ Domain
            Application ~~~~ Domain
            Application ~~~~ Domain
            Application ~~~~ Domain
            Application ~~~~ Domain
            Application ---> Domain

            ApplicationService    ---> ApplicationContract
            InfrastructureAdapter -.-o ApplicationContract
            InfrastructureAdapter ~~~~ ApplicationContract
        end
    end

    classDef nsDepth_1 fill:#1D2021,stroke:#1D2021,color:#7C6F64,stroke-width:8px
    classDef nsDepth_2 fill:#282828,stroke:#282828,color:#7C6F64,stroke-width:8px
    classDef nsDepth_3 fill:#3C3836,stroke:#3C3836,color:#7C6F64,stroke-width:8px
    classDef nsDepth_4 fill:#504945,stroke:#504945,color:#1D2021,stroke-width:8px
    classDef nsDepth_5 fill:#665C54,stroke:#665C54,color:#1D2021,stroke-width:8px
    classDef nsDepth_6 fill:#7C6F64,stroke:#7C6F64,color:#1D2021,stroke-width:16px
    
    classDef implementation fill:#1D2021,stroke:#282828,font-weight:bold,stroke-width:8px,color:#EBDBB2
    classDef contract fill:#EBDBB2,stroke:#A89984,font-weight:bold,stroke-width:8px,color:#665C54

    class Subdomains,SubdomainsGroup nsDepth_1
    class Core,SupportingSubdomains,GenericSubdomains nsDepth_2
    class Infrastructure,Application,Domain,SupportingSubDomainsBoundedContexts,GenericSubdomainsBoundedContexts nsDepth_3
    class InfrastructureAdapter,ApplicationContract nsDepth_4
    class DomainService,DomainSchema,InfrastructureQuery,InfrastructureCommand,InfrastructureGateway,ApplicationService,ApplicationQuery,ApplicationCommand,ApplicationGateway nsDepth_5
    class InfrastructureCommandDownstream,InfrastructureCommandUpstream,InfrastructureQueryDownstream,InfrastructureQueryUpstream,InfrastructureGatewayUpstream,InfrastructureGatewayDownstream,ApplicationQueryContractUpstream,ApplicationQueryContractDownstream,ApplicationCommandContractUpstream,ApplicationCommandContractDownstream,ApplicationGatewayInbound,ApplicationGatewayOutbound nsDepth_6
    
    class DomainEntity,DomainValueObject,ApplicationQueryContractUpstreamInterface,ApplicationQueryContractDownstreamInterface,ApplicationCommandContractUpstreamInterface,ApplicationCommandContractDownstreamInterface,ApplicationGatewayUpstream,ApplicationGatewayDownstream contract
    class InfrastructureQueryUpstreamAdapter,InfrastructureQueryDownstreamAdapter,InfrastructureCommandUpstreamAdapter,InfrastructureCommandDownstreamAdapter,DomainFactory,DomainAggregate,InfrastructureGatewayUpstreamAdapter,InfrastructureGatewayDownstreamAdapter implementation